### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by tracygardner** [raspberrypilearning/scouts-team-chooser#1]
- [x] Not sure there's any value to introducing then 'when green flag' code before the variable and list. 
- [x] Leader instructions should include when to use the team chooser - to pick groups for a game or activity. 
- [x]  'Then give it a name (e.g., Number of teams).' At this level, just tell them what to name it. 
- [x] Explain that the answer block stores your answer to the question in the 'answer' variable, otherwise it's hard to understand why you are using it. 
- [x] Using this technique with variables i, j and temp seems quite advanced for a stage 2 resource. They won't have any understanding of such naming. How about just choosing random names and then removing them from the list like this https://scratch.mit.edu/projects/299629076/editor/
- [x] Entering all of the names every time gets tired quickly. Maybe just have them enter the names using the '+' on the list monitor on stage or in code. Could add user input at the end after testing maybe?
- [x] Part 2: Shuffling your list of names - would be good to explain why you are shuffling the list

**Comment by daraghbroderick** [comment]
Added section on using some hard coded values during testing to address tedious name typing.
Shuffling list no longer included.
